#include <stdlib.h>
#include <string.h>
#include "itemnames.h"

struct ITEMNAME uniquenames[] = {
	{ 0, "The Gnasher" }, 
	{ 1, "Deathspade" }, 
	{ 2, "Bladebone" }, 
	{ 3, "Mindrend" }, 
	{ 4, "Rakescar" }, 
	{ 5, "Fechmars Axe" }, 
	{ 6, "Goreshovel" }, 
	{ 7, "The Chieftan" }, 
	{ 8, "Brainhew" }, 
	{ 9, "The Humongous" }, 
	{ 10, "Iros Torch" }, 
	{ 11, "Maelstromwrath" }, 
	{ 12, "Gravenspine" }, 
	{ 13, "Umes Lament" }, 
	{ 14, "Felloak" }, 
	{ 15, "Knell Striker" }, 
	{ 16, "Rusthandle" }, 
	{ 17, "Stormeye" }, 
	{ 18, "Stoutnail" }, 
	{ 19, "Crushflange" }, 
	{ 20, "Bloodrise" }, 
	{ 21, "The Generals Tan Do Li Ga" }, 
	{ 22, "Ironstone" }, 
	{ 23, "Bonesob" }, 
	{ 24, "Steeldriver" }, 
	{ 25, "Rixots Keen" }, 
	{ 26, "Blood Crescent" }, 
	{ 27, "Krintizs Skewer" }, 
	{ 28, "Gleamscythe" }, 
	{ 29, "Azurewrath" }, 
	{ 30, "Griswolds Edge" }, 
	{ 31, "Hellplague" }, 
	{ 32, "Culwens Point" }, 
	{ 33, "Shadowfang" }, 
	{ 34, "Soulflay" }, 
	{ 35, "Kinemils Awl" }, 
	{ 36, "Blacktongue" }, 
	{ 37, "Ripsaw" }, 
	{ 38, "The Patriarch" }, 
	{ 39, "Gull" }, 
	{ 40, "The Diggler" }, 
	{ 41, "The Jade Tan Do" }, 
	{ 42, "Irices Shard" }, 
	{ 43, "The Dragon Chang" }, 
	{ 44, "Razortine" }, 
	{ 45, "Bloodthief" }, 
	{ 46, "Lance of Yaggai" }, 
	{ 47, "The Tannr Gorerod" }, 
	{ 48, "Dimoaks Hew" }, 
	{ 49, "Steelgoad" }, 
	{ 50, "Soul Harvest" }, 
	{ 51, "The Battlebranch" }, 
	{ 52, "Woestave" }, 
	{ 53, "The Grim Reaper" }, 
	{ 54, "Bane Ash" }, 
	{ 55, "Serpent Lord" }, 
	{ 56, "Lazarus Spire" }, 
	{ 57, "The Salamander" }, 
	{ 58, "The Iron Jang Bong" }, 
	{ 59, "Pluckeye" }, 
	{ 60, "Witherstring" }, 
	{ 61, "Rimeraven" }, 
	{ 62, "Piercerib" }, 
	{ 63, "Pullspite" }, 
	{ 64, "Wizendraw" }, 
	{ 65, "Hellclap" }, 
	{ 66, "Blastbark" }, 
	{ 67, "Leadcrow" }, 
	{ 68, "Ichorsting" }, 
	{ 69, "Hellcast" }, 
	{ 70, "Doomspittle" }, 
	{ 71, "War Bonnet" }, 
	{ 72, "Tarnhelm" }, 
	{ 73, "Coif of Glory" }, 
	{ 74, "Duskdeep" }, 
	{ 75, "Wormskull" }, 
	{ 76, "Howltusk" }, 
	{ 77, "Undead Crown" }, 
	{ 78, "The Face of Horror" }, 
	{ 79, "Greyform" }, 
	{ 80, "Blinkbats Form" }, 
	{ 81, "The Centurion" }, 
	{ 82, "Twitchthroe" }, 
	{ 83, "Darkglow" }, 
	{ 84, "Hawkmail" }, 
	{ 85, "Sparking Mail" }, 
	{ 86, "Venomsward" }, 
	{ 87, "Iceblink" }, 
	{ 88, "Boneflesh" }, 
	{ 89, "Rockfleece" }, 
	{ 90, "Rattlecage" }, 
	{ 91, "Goldskin" }, 
	{ 92, "Victors Silk" }, 
	{ 93, "Heavenly Garb" }, 
	{ 94, "Pelta Lunata" }, 
	{ 95, "Umbral Disk" }, 
	{ 96, "Stormguild" }, 
	{ 97, "Wall of the Eyeless" }, 
	{ 98, "Swordback Hold" }, 
	{ 99, "Steelclash" }, 
	{ 100, "Bverrit Keep" }, 
	{ 101, "The Ward" }, 
	{ 102, "The Hand of Broc" }, 
	{ 103, "Bloodfist" }, 
	{ 104, "Chance Guards" }, 
	{ 105, "Magefist" }, 
	{ 106, "Frostburn" }, 
	{ 107, "Hotspur" }, 
	{ 108, "Gorefoot" }, 
	{ 109, "Treads of Cthon" }, 
	{ 110, "Goblin Toe" }, 
	{ 111, "Tearhaunch" }, 
	{ 112, "Lenyms Cord" }, 
	{ 113, "Snakecord" }, 
	{ 114, "Nightsmoke" }, 
	{ 115, "Goldwrap" }, 
	{ 116, "Bladebuckle" }, 
	{ 117, "Nokozan Relic" }, 
	{ 118, "The Eye of Etlich" }, 
	{ 119, "The Mahim-Oak Curio" }, 
	{ 120, "Nagelring" }, 
	{ 121, "Manald Heal" }, 
	{ 122, "The Stone of Jordan" }, 
	{ 123, "Amulet of the Viper" }, 
	{ 124, "Staff of Kings" }, 
	{ 125, "Horadric Staff" }, 
	{ 126, "Hell Forge Hammer" }, 
	{ 127, "KhalimFlail" }, 
	{ 128, "SuperKhalimFlail" }, 
	{ 129, "Coldkill" }, 
	{ 130, "Butcher's Pupil" }, 
	{ 131, "Islestrike" }, 
	{ 132, "Pompe's Wrath" }, 
	{ 133, "Guardian Naga" }, 
	{ 134, "Warlord's Trust" }, 
	{ 135, "Spellsteel" }, 
	{ 136, "Stormrider" }, 
	{ 137, "Boneslayer Blade" }, 
	{ 138, "The Minataur" }, 
	{ 139, "Suicide Branch" }, 
	{ 140, "Carin Shard" }, 
	{ 141, "Arm of King Leoric" }, 
	{ 142, "Blackhand Key" }, 
	{ 143, "Dark Clan Crusher" }, 
	{ 144, "Zakarum's Hand" }, 
	{ 145, "The Fetid Sprinkler" }, 
	{ 146, "Hand of Blessed Light" }, 
	{ 147, "Fleshrender" }, 
	{ 148, "Sureshrill Frost" }, 
	{ 149, "Moonfall" }, 
	{ 150, "Baezil's Vortex" }, 
	{ 151, "Earthshaker" }, 
	{ 152, "Bloodtree Stump" }, 
	{ 153, "The Gavel of Pain" }, 
	{ 154, "Bloodletter" }, 
	{ 155, "Coldsteel Eye" }, 
	{ 156, "Hexfire" }, 
	{ 157, "Blade of Ali Baba" }, 
	{ 158, "Ginther's Rift" }, 
	{ 159, "Headstriker" }, 
	{ 160, "Plague Bearer" }, 
	{ 161, "The Atlantian" }, 
	{ 162, "Crainte Vomir" }, 
	{ 163, "Bing Sz Wang" }, 
	{ 164, "The Vile Husk" }, 
	{ 165, "Cloudcrack" }, 
	{ 166, "Todesfaelle Flamme" }, 
	{ 167, "Swordguard" }, 
	{ 168, "Spineripper" }, 
	{ 169, "Heart Carver" }, 
	{ 170, "Blackbog's Sharp" }, 
	{ 171, "Stormspike" }, 
	{ 172, "The Impaler" }, 
	{ 173, "Kelpie Snare" }, 
	{ 174, "Soulfeast Tine" }, 
	{ 175, "Hone Sundan" }, 
	{ 176, "Spire of Honor" }, 
	{ 177, "The Meat Scraper" }, 
	{ 178, "Blackleach Blade" }, 
	{ 179, "Athena's Wrath" }, 
	{ 180, "Pierre Tombale Couant" }, 
	{ 181, "Husoldal Evo" }, 
	{ 182, "Grim's Burning Dead" }, 
	{ 183, "Razorswitch" }, 
	{ 184, "Ribcracker" }, 
	{ 185, "Chromatic Ire" }, 
	{ 186, "Warpspear" }, 
	{ 187, "Skullcollector" }, 
	{ 188, "Skystrike" }, 
	{ 189, "Riphook" }, 
	{ 190, "Kuko Shakaku" }, 
	{ 191, "Endlesshail" }, 
	{ 192, "Whichwild String" }, 
	{ 193, "Cliffkiller" }, 
	{ 194, "Magewrath" }, 
	{ 195, "Godstrike Arch" }, 
	{ 196, "Langer Briser" }, 
	{ 197, "Pus Spiter" }, 
	{ 198, "Buriza-Do Kyanon" }, 
	{ 199, "Demon Machine" }, 
	{ 200, "Peasent Crown" }, 
	{ 201, "Rockstopper" }, 
	{ 202, "Stealskull" }, 
	{ 203, "Darksight Helm" }, 
	{ 204, "Valkiry Wing" }, 
	{ 205, "Crown of Thieves" }, 
	{ 206, "Blackhorn's Face" }, 
	{ 207, "Vampiregaze" }, 
	{ 208, "The Spirit Shroud" }, 
	{ 209, "Skin of the Vipermagi" }, 
	{ 210, "Skin of the Flayerd One" }, 
	{ 211, "Ironpelt" }, 
	{ 212, "Spiritforge" }, 
	{ 213, "Crow Caw" }, 
	{ 214, "Shaftstop" }, 
	{ 215, "Duriel's Shell" }, 
	{ 216, "Skullder's Ire" }, 
	{ 217, "Guardian Angel" }, 
	{ 218, "Toothrow" }, 
	{ 219, "Atma's Wail" }, 
	{ 220, "Black Hades" }, 
	{ 221, "Corpsemourn" }, 
	{ 222, "Que-Hegan's Wisdon" }, 
	{ 223, "Visceratuant" }, 
	{ 224, "Mosers Blessed Circle" }, 
	{ 225, "Stormchaser" }, 
	{ 226, "Tiamat's Rebuke" }, 
	{ 227, "Kerke's Sanctuary" }, 
	{ 228, "Radimant's Sphere" }, 
	{ 229, "Lidless Wall" }, 
	{ 230, "Lance Guard" }, 
	{ 231, "Venom Grip" }, 
	{ 232, "Gravepalm" }, 
	{ 233, "Ghoulhide" }, 
	{ 234, "Lavagout" }, 
	{ 235, "Hellmouth" }, 
	{ 236, "Infernostride" }, 
	{ 237, "Waterwalk" }, 
	{ 238, "Silkweave" }, 
	{ 239, "Wartraveler" }, 
	{ 240, "Gorerider" }, 
	{ 241, "String of Ears" }, 
	{ 242, "Razortail" }, 
	{ 243, "Gloomstrap" }, 
	{ 244, "Snowclash" }, 
	{ 245, "Thudergod's Vigor" }, 
	{ 246, "Harlequin Crest" }, 
	{ 247, "Veil of Steel" }, 
	{ 248, "The Gladiator's Bane" }, 
	{ 249, "Arkaine's Valor" }, 
	{ 250, "Blackoak Shield" }, 
	{ 251, "Stormshield" }, 
	{ 252, "Hellslayer" }, 
	{ 253, "Messerschmidt's Reaver" }, 
	{ 254, "Baranar's Star" }, 
	{ 255, "Schaefer's Hammer" }, 
	{ 256, "The Cranium Basher" }, 
	{ 257, "Lightsabre" }, 
	{ 258, "Doombringer" }, 
	{ 259, "The Grandfather" }, 
	{ 260, "Wizardspike" }, 
	{ 261, "Constricting Ring" }, 
	{ 262, "Stormspire" }, 
	{ 263, "Eaglehorn" }, 
	{ 264, "Windforce" }, 
	{ 265, "Bul Katho's Wedding Band" }, 
	{ 266, "The Cat's Eye" }, 
	{ 267, "The Rising Sun" }, 
	{ 268, "Crescent Moon" }, 
	{ 269, "Mara's Kaleidoscope" }, 
	{ 270, "Atma's Scarab" }, 
	{ 271, "Dwarf Star" }, 
	{ 272, "Raven Frost" }, 
	{ 273, "Highlord's Wrath" }, 
	{ 274, "Saracen's Chance" }, 
	{ 275, "Arreat's Face" }, 
	{ 276, "Homunculus" }, 
	{ 277, "Titan's Revenge" }, 
	{ 278, "Lycander's Aim" }, 
	{ 279, "Lycander's Flank" }, 
	{ 280, "The Oculus" }, 
	{ 281, "Herald of Zakarum" }, 
	{ 282, "Cutthroat1" }, 
	{ 283, "Jalal's Mane" }, 
	{ 284, "The Scalper" }, 
	{ 285, "Bloodmoon" }, 
	{ 286, "Djinnslayer" }, 
	{ 287, "Deathbit" }, 
	{ 288, "Warshrike" }, 
	{ 289, "Gutsiphon" }, 
	{ 290, "Razoredge" }, 
	{ 291, "Gore Ripper" }, 
	{ 292, "Demonlimb" }, 
	{ 293, "Steelshade" }, 
	{ 294, "Tomb Reaver" }, 
	{ 295, "Deaths's Web" }, 
	{ 296, "Nature's Peace" }, 
	{ 297, "Azurewrath" }, 
	{ 298, "Seraph's Hymn" }, 
	{ 299, "Zakarum's Salvation" }, 
	{ 300, "Fleshripper" }, 
	{ 301, "Odium" }, 
	{ 302, "Horizon's Tornado" }, 
	{ 303, "Stone Crusher" }, 
	{ 304, "Jadetalon" }, 
	{ 305, "Shadowdancer" }, 
	{ 306, "Cerebus" }, 
	{ 307, "Tyrael's Might" }, 
	{ 308, "Souldrain" }, 
	{ 309, "Runemaster" }, 
	{ 310, "Deathcleaver" }, 
	{ 311, "Executioner's Justice" }, 
	{ 312, "Stoneraven" }, 
	{ 313, "Leviathan" }, 
	{ 314, "Larzuk's Champion" }, 
	{ 315, "Wisp" }, 
	{ 316, "Gargoyle's Bite" }, 
	{ 317, "Lacerator" }, 
	{ 318, "Mang Song's Lesson" }, 
	{ 319, "Viperfork" }, 
	{ 320, "Ethereal Edge" }, 
	{ 321, "Demonhorn's Edge" }, 
	{ 322, "The Reaper's Toll" }, 
	{ 323, "Spiritkeeper" }, 
	{ 324, "Hellrack" }, 
	{ 325, "Alma Negra" }, 
	{ 326, "Darkforge Spawn" }, 
	{ 327, "Widowmaker" }, 
	{ 328, "Bloodraven's Charge" }, 
	{ 329, "Ghostflame" }, 
	{ 330, "Shadowkiller" }, 
	{ 331, "Gimmershred" }, 
	{ 332, "Griffon's Eye" }, 
	{ 333, "Windhammer" }, 
	{ 334, "Thunderstroke" }, 
	{ 335, "Giantmaimer" }, 
	{ 336, "Demon's Arch" }, 
	{ 337, "Boneflame" }, 
	{ 338, "Steelpillar" }, 
	{ 339, "Nightwing's Veil" }, 
	{ 340, "Crown of Ages" }, 
	{ 341, "Andariel's Visage" }, 
	{ 342, "Darkfear" }, 
	{ 343, "Dragonscale" }, 
	{ 344, "Steel Carapice" }, 
	{ 345, "Medusa's Gaze" }, 
	{ 346, "Ravenlore" }, 
	{ 347, "Boneshade" }, 
	{ 348, "Nethercrow" }, 
	{ 349, "Flamebellow" }, 
	{ 350, "Fathom" }, 
	{ 351, "Wolfhowl" }, 
	{ 352, "Spirit Ward" }, 
	{ 353, "Kira's Guardian" }, 
	{ 354, "Ormus' Robes" }, 
	{ 355, "Gheed's Fortune" }, 
	{ 356, "Stormlash" }, 
	{ 357, "Halaberd's Reign" }, 
	{ 358, "Warriv's Warder" }, 
	{ 359, "Spike Thorn" }, 
	{ 360, "Dracul's Grasp" }, 
	{ 361, "Frostwind" }, 
	{ 362, "Templar's Might" }, 
	{ 363, "Eschuta's temper" }, 
	{ 364, "Firelizard's Talons" }, 
	{ 365, "Sandstorm Trek" }, 
	{ 366, "Marrowwalk" }, 
	{ 367, "Heaven's Light" }, 
	{ 368, "Merman's Speed" }, 
	{ 369, "Arachnid Mesh" }, 
	{ 370, "Nosferatu's Coil" }, 
	{ 371, "Metalgrid" }, 
	{ 372, "Verdugo's Hearty Cord" }, 
	{ 373, "Sigurd's Staunch" }, 
	{ 374, "Carrion Wind" }, 
	{ 375, "Giantskull" }, 
	{ 376, "Ironward" }, 
	{ 377, "Annihilus" }, 
	{ 378, "Arioc's Needle" }, 
	{ 379, "Cranebeak" }, 
	{ 380, "Nord's Tenderizer" }, 
	{ 381, "Earthshifter" }, 
	{ 382, "Wraithflight" }, 
	{ 383, "Bonehew" }, 
	{ 384, "Ondal's Wisdom" }, 
	{ 385, "The Reedeemer" }, 
	{ 386, "Headhunter's Glory" }, 
	{ 387, "Steelrend" }, 
	{ 388, "Rainbow Facet" }, 
	{ 389, "Rainbow Facet" }, 
	{ 390, "Rainbow Facet" }, 
	{ 391, "Rainbow Facet" }, 
	{ 392, "Rainbow Facet" }, 
	{ 393, "Rainbow Facet" }, 
	{ 394, "Rainbow Facet" }, 
	{ 395, "Rainbow Facet" }, 
	{ 396, "Hellfire Torch" }, 
	{ 0, NULL }
};

struct ITEMNAME setnames[] = {
	{ 0, "Civerb's Vestments" }, 
	{ 1, "Hsarus' Defense" }, 
	{ 2, "Cleglaw's Brace" }, 
	{ 3, "Iratha's Finery" }, 
	{ 4, "Isenhart's Armory" }, 
	{ 5, "Vidala's Rig" }, 
	{ 6, "Milabrega's Regalia" }, 
	{ 7, "Cathan's Traps" }, 
	{ 8, "Tancred's Battlegear" }, 
	{ 9, "Sigon's Complete Steel" }, 
	{ 10, "Infernal Tools" }, 
	{ 11, "Berserker's Garb" }, 
	{ 12, "Death's Disguise" }, 
	{ 13, "Angelical Raiment" }, 
	{ 14, "Arctic Gear" }, 
	{ 15, "Arcanna's Tricks" }, 
	{ 16, "Natalya's Odium" }, 
	{ 17, "Aldur's Watchtower" }, 
	{ 18, "Immortal King" }, 
	{ 19, "Tal Rasha's Wrappings" }, 
	{ 20, "Griswold's Legacy" }, 
	{ 21, "Trang-Oul's Avatar" }, 
	{ 22, "M'avina's Battle Hymn" }, 
	{ 23, "The Disciple" }, 
	{ 24, "Heaven's Brethren" }, 
	{ 25, "Orphan's Call" }, 
	{ 26, "Hwanin's Majesty" }, 
	{ 27, "Sazabi's Grand Tribute" }, 
	{ 28, "Bul-Kathos' Children" }, 
	{ 29, "Cow King's Leathers" }, 
	{ 30, "Naj's Ancient Set" }, 
	{ 31, "McAuley's Folly" }, 
	{ 0, NULL }

};

struct ITEMSETNAME setitemnames[] = {
	{ 0, "lrg", "Civerb's Ward" }, 
	{ 0, "amu", "Civerb's Icon" }, 
	{ 0, "gsc", "Civerb's Cudgel" }, 
	{ 1, "mbt", "Hsarus' Iron Heel" }, 
	{ 1, "buc", "Hsarus' Iron Fist" }, 
	{ 1, "mbl", "Hsarus' Iron Stay" }, 
	{ 2, "lsd", "Cleglaw's Tooth" }, 
	{ 2, "sml", "Cleglaw's Claw" }, 
	{ 2, "mgl", "Cleglaw's Pincers" }, 
	{ 3, "amu", "Iratha's Collar" }, 
	{ 3, "tgl", "Iratha's Cuff" }, 
	{ 3, "crn", "Iratha's Coil" }, 
	{ 3, "tbl", "Iratha's Cord" }, 
	{ 4, "bsd", "Isenhart's Lightbrand" }, 
	{ 4, "gts", "Isenhart's Parry" }, 
	{ 4, "brs", "Isenhart's Case" }, 
	{ 4, "fhl", "Isenhart's Horns" }, 
	{ 5, "lbb", "Vidala's Barb" }, 
	{ 5, "tbt", "Vidala's Fetlock" }, 
	{ 5, "lea", "Vidala's Ambush" }, 
	{ 5, "amu", "Vidala's Snare" }, 
	{ 6, "kit", "Milabrega's Orb" }, 
	{ 6, "wsp", "Milabrega's Rod" }, 
	{ 6, "crn", "Milabrega's Diadem" }, 
	{ 6, "aar", "Milabrega's Robe" }, 
	{ 7, "bst", "Cathan's Rule" }, 
	{ 7, "chn", "Cathan's Mesh" }, 
	{ 7, "msk", "Cathan's Visage" }, 
	{ 7, "amu", "Cathan's Sigil" }, 
	{ 7, "rin", "Cathan's Seal" }, 
	{ 8, "mpi", "Tancred's Crowbill" }, 
	{ 8, "ful", "Tancred's Spine" }, 
	{ 8, "lbt", "Tancred's Hobnails" }, 
	{ 8, "amu", "Tancred's Weird" }, 
	{ 8, "bhm", "Tancred's Skull" }, 
	{ 9, "hgl", "Sigon's Gage" }, 
	{ 9, "ghm", "Sigon's Visor" }, 
	{ 9, "gth", "Sigon's Shelter" }, 
	{ 9, "hbt", "Sigon's Sabot" }, 
	{ 9, "hbl", "Sigon's Wrap" }, 
	{ 9, "tow", "Sigon's Guard" }, 
	{ 10, "cap", "Infernal Cranium" }, 
	{ 10, "gwn", "Infernal Torch" }, 
	{ 10, "tbl", "Infernal Sign" }, 
	{ 11, "hlm", "Berserker's Headgear" }, 
	{ 11, "spl", "Berserker's Hauberk" }, 
	{ 11, "2ax", "Berserker's Hatchet" }, 
	{ 12, "lgl", "Death's Hand" }, 
	{ 12, "lbl", "Death's Guard" }, 
	{ 12, "wsd", "Death's Touch" }, 
	{ 13, "sbr", "Angelic Sickle" }, 
	{ 13, "rng", "Angelic Mantle" }, 
	{ 13, "rin", "Angelic Halo" }, 
	{ 13, "amu", "Angelic Wings" }, 
	{ 14, "swb", "Arctic Horn" }, 
	{ 14, "qui", "Arctic Furs" }, 
	{ 14, "vbl", "Arctic Binding" }, 
	{ 14, "tgl", "Arctic Mitts" }, 
	{ 15, "amu", "Arcanna's Sign" }, 
	{ 15, "wst", "Arcanna's Deathwand" }, 
	{ 15, "skp", "Arcanna's Head" }, 
	{ 15, "ltp", "Arcanna's Flesh" }, 
	{ 16, "xh9", "Natalya's Totem" }, 
	{ 16, "7qr", "Natalya's Mark" }, 
	{ 16, "ucl", "Natalya's Shadow" }, 
	{ 16, "xmb", "Natalya's Soul" }, 
	{ 17, "dr8", "Aldur's Stony Gaze" }, 
	{ 17, "uul", "Aldur's Deception" }, 
	{ 17, "9mt", "Aldur's Gauntlet" }, 
	{ 17, "xtb", "Aldur's Advance" }, 
	{ 18, "ba5", "Immortal King's Will" }, 
	{ 18, "uar", "Immortal King's Soul Cage " }, 
	{ 18, "zhb", "Immortal King's Detail" }, 
	{ 18, "xhg", "Immortal King's Forge" }, 
	{ 18, "xhb", "Immortal King's Pillar" }, 
	{ 18, "7m7", "Immortal King's Stone Crusher" }, 
	{ 19, "zmb", "Tal Rasha's Fire-Spun Cloth" }, 
	{ 19, "amu", "Tal Rasha's Adjudication" }, 
	{ 19, "oba", "Tal Rasha's Lidless Eye" }, 
	{ 19, "uth", "Tal Rasha's Howling Wind" }, 
	{ 19, "xsk", "Tal Rasha's Horadric Crest" }, 
	{ 20, "urn", "Griswold's Valor" }, 
	{ 20, "xar", "Griswold's Heart" }, 
	{ 20, "7ws", "Griswolds's Redemption" }, 
	{ 20, "paf", "Griswold's Honor" }, 
	{ 21, "uh9", "Trang-Oul's Guise" }, 
	{ 21, "xul", "Trang-Oul's Scales" }, 
	{ 21, "ne9", "Trang-Oul's Wing" }, 
	{ 21, "xmg", "Trang-Oul's Claws" }, 
	{ 21, "utc", "Trang-Oul's Girth" }, 
	{ 22, "ci3", "M'avina's True Sight" }, 
	{ 22, "uld", "M'avina's Embrace" }, 
	{ 22, "xtg", "M'avina's Icy Clutch" }, 
	{ 22, "zvb", "M'avina's Tenet" }, 
	{ 22, "amc", "M'avina's Caster" }, 
	{ 23, "amu", "Telling of Beads" }, 
	{ 23, "ulg", "Laying of Hands" }, 
	{ 23, "xlb", "Rite of Passage" }, 
	{ 23, "uui", "Spiritual Custodian" }, 
	{ 23, "umc", "Credendum" }, 
	{ 24, "7ma", "Dangoon's Teaching" }, 
	{ 24, "uts", "Heaven's Taebaek" }, 
	{ 24, "xrs", "Haemosu's Adament" }, 
	{ 24, "uhm", "Ondal's Almighty" }, 
	{ 25, "xhm", "Guillaume's Face" }, 
	{ 25, "ztb", "Wilhelm's Pride" }, 
	{ 25, "xvg", "Magnus' Skin" }, 
	{ 25, "xml", "Wihtstan's Guard" }, 
	{ 26, "xrn", "Hwanin's Splendor" }, 
	{ 26, "xcl", "Hwanin's Refuge" }, 
	{ 26, "mbl", "Hwanin's Seal" }, 
	{ 26, "9vo", "Hwanin's Justice" }, 
	{ 27, "7ls", "Sazabi's Cobalt Redeemer" }, 
	{ 27, "upl", "Sazabi's Ghost Liberator" }, 
	{ 27, "xhl", "Sazabi's Mental Sheath" }, 
	{ 28, "7gd", "Bul-Kathos' Sacred Charge" }, 
	{ 28, "7wd", "Bul-Kathos' Tribal Guardian" }, 
	{ 29, "xap", "Cow King's Horns" }, 
	{ 29, "stu", "Cow King's Hide" }, 
	{ 29, "vbt", "Cow King's Hoofs" }, 
	{ 30, "6cs", "Naj's Puzzler" }, 
	{ 30, "ult", "Naj's Light Plate" }, 
	{ 30, "ci0", "Naj's Circlet" }, 
	{ 31, "cap", "McAuley's Paragon" }, 
	{ 31, "vbt", "McAuley's Riprap" }, 
	{ 31, "vgl", "McAuley's Taboo" }, 
	{ 31, "bwn", "McAuley's Superstition" }, 
	{ 0, NULL, NULL }
};

struct ITEMNAME*
findUniqueName(uint16_t id)
{
	ITEMNAME* in = uniquenames;
	while (in->name != NULL) {
		if (in->id == id)
			return in;
		in++;
	}
	return NULL;
}

struct ITEMNAME*
findSetName(uint16_t id)
{
	ITEMNAME* in = setnames;
	while (in->name != NULL) {
		if (in->id == id)
			return in;
		in++;
	}
	return NULL;
}

struct ITEMSETNAME*
findSetItemName(uint16_t setid, uint8_t* type)
{
	ITEMSETNAME* in = setitemnames;
	while (in->name != NULL) {
		if (in->setid == setid && !strncmp(in->type, (char*)type, strlen(in->type)))
			return in;
		in++;
	}
	return NULL;
}
