#!/bin/sh
./import.pl amazon.xml
./import.pl armor.xml
./import.pl assassin.xml
./import.pl axe.xml
./import.pl barbarian_helms.xml
./import.pl belts.xml
./import.pl boots.xml
./import.pl bow.xml
./import.pl circlets.xml
./import.pl crossbows.xml
./import.pl dagger.xml
./import.pl druid_pelts.xml
./import.pl gloves.xml
./import.pl helms.xml
./import.pl javelin.xml
./import.pl jewelry.xml
./import.pl mace.xml
./import.pl necro_head.xml
./import.pl paladin_shields.xml
./import.pl polearms.xml
./import.pl scepters.xml
./import.pl shield.xml
./import.pl sorceress.xml
./import.pl spears.xml
./import.pl staves.xml
./import.pl swords.xml
./import.pl throwing.xml
./import.pl wands.xml
