#!/usr/bin/perl -w

use strict;

print "/*
 * This file is automatically generated - DO NOT EDIT
 */
#include <stdlib.h>
#include \"item.h\"

struct ITEMTYPE itemtypes[] = {
";

open F, "<Armor.txt" or die;
<F>;
while(<F>) {
	chop; my @a = split(/\t/); next unless $a[17];
	printf "\t{ \"%s\", \"%s\", ITEMTYPE_ARMOR }, \n", $a[0], $a[17];
}
close F;

open F, "<Weapons.txt" or die;
<F>;
while(<F>) {
	chop; my @a = split(/\t/); next unless $a[3];
	my $type = "ITEMTYPE_WEAPON";
	$type .= "|ITEMTYPE_STACKABLE" if $a[43];
	printf "\t{ \"%s\", \"%s\", %s }, \n", $a[0], $a[3], $type;
}
close F;

open F, "<Misc.txt" or die;
<F>;
while(<F>) {
	chop; my @a = split(/\t/);
	next unless $a[13];
	my $type;
	if ($a[0] eq "Town Portal Book" or $a[0] eq "Identify Book") {
		$type = "ITEMTYPE_TOME";
	} else {
		$type = "ITEMTYPE_MISC";
	}
	$type .= "|ITEMTYPE_STACKABLE" if $a[43];
	printf "\t{ \"%s\", \"%s\", %s }, \n", $a[0], $a[13], $type;
}
close F;

printf "\t{ NULL, NULL, 0 }
};
";
